import type { HistoryItem, Property } from "../types";

export const GRAFTON_CBD = { lat: -29.6892, lng: 152.9353 };

export const HISTORY: HistoryItem[] = [
  { id: "h1", time: "Now", address: "12 Example St", suburb: "Grafton" },
  { id: "h2", time: "12:41", address: "47 River Rd", suburb: "South Grafton" },
  { id: "h3", time: "11:08", address: "8 Breimba St", suburb: "Junction Hill" },
  { id: "h4", time: "Yesterday", address: "201 Prince St", suburb: "Grafton" },
  { id: "h5", time: "Yesterday", address: "15 Oliver St", suburb: "Grafton" },
  { id: "h6", time: "Mon", address: "3 Villiers St", suburb: "Grafton" },
  { id: "h7", time: "Mon", address: "88 Fry St", suburb: "Grafton" },
];

export const PROPERTIES: Property[] = [
  {
    address: "12 Example St, Grafton",
    suburb: "Grafton",
    lat: -29.69,
    lng: 152.93,
    bedrooms: 3,
    bathrooms: 1,
    carSpaces: 1,
    landM2: 612,
    yearBuilt: 1978,
    floodRisk: "Low",
    bushfireRisk: "Low",
    zoning: "R2 Low Density",
    councilNotes: "Standard building envelope.",
    source: "cache",
  },
  {
    address: "47 River Rd, South Grafton",
    suburb: "South Grafton",
    lat: -29.71,
    lng: 152.92,
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    landM2: 820,
    yearBuilt: 1992,
    floodRisk: "Medium",
    bushfireRisk: "Low",
    zoning: "R1 General",
    source: "dataset",
  },
  {
    address: "8 Breimba St, Junction Hill",
    suburb: "Junction Hill",
    lat: -29.64,
    lng: 152.93,
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    landM2: 540,
    yearBuilt: 2004,
    floodRisk: "Low",
    bushfireRisk: "Medium",
    zoning: "R2 Low Density",
    source: "dataset",
  },
  {
    address: "201 Prince St, Grafton",
    suburb: "Grafton",
    lat: -29.68,
    lng: 152.93,
    bedrooms: 2,
    bathrooms: 1,
    carSpaces: 1,
    landM2: 410,
    yearBuilt: 1964,
    floodRisk: "Low",
    bushfireRisk: "Low",
    zoning: "B4 Mixed Use",
    source: "cache",
  },
  {
    address: "15 Oliver St, Grafton",
    suburb: "Grafton",
    lat: -29.695,
    lng: 152.935,
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    landM2: 690,
    yearBuilt: 1988,
    floodRisk: "Low",
    bushfireRisk: "Low",
    zoning: "R2 Low Density",
    source: "dataset",
  },
];
